version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: space_php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      .env
  db:
    image: mysql:8
    restart: always
    container_name: space_db
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network
    env_file:
      .env


volumes:
  dbdata:

networks:
  app-network:
